CREATE TABLE `car_event_logs` (
   `log_id` BINARY(16) NOT NULL PRIMARY KEY,
   `packet_ver` SMALLINT UNSIGNED NOT NULL,
   `event_type` VARCHAR(10) NOT NULL,
   `tx_uid` BINARY(16) NOT NULL,
   `car_id` VARCHAR(32) NOT NULL,
   `terminal_id` VARCHAR(16) NOT NULL,
   `manufacture_id` VARCHAR(16) NOT NULL,
   `device_id` VARCHAR(16) NOT NULL,
   `gps_cond` CHAR(1) NOT NULL,
   `gps_lat` DECIMAL(9, 6) NOT NULL,
   `gps_lon` DECIMAL(10, 6) NOT NULL,
   `mdt_angle` SMALLINT UNSIGNED NOT NULL,
   `mdt_speed` TINYINT UNSIGNED NOT NULL,
   `mdt_mileage_sum` MEDIUMINT UNSIGNED NOT NULL,
   `mdt_battery_voltage` SMALLINT UNSIGNED DEFAULT NULL,
   `mdt_ignition_onTime` DATETIME DEFAULT NULL,
   `mdt_ignition_offTime` DATETIME DEFAULT NULL,
   `occurred_at` DATETIME NOT NULL,
   `sent_at` DATETIME NOT NULL,
   `received_at` DATETIME NOT NULL,
);
