name: Deploy Dev OCI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - CICD

concurrency:
  group: 'deploy-dev-oci-hq'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Caching Gradle dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Build the project
        run: ./gradlew --build-cache :roadeye-api:roadeye-api-hq:build

      - name: Verify SSH host
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          mkdir -p ~/.ssh
          rm -f ~/.ssh/known_hosts
          ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          JAR_PATH: roadeye-api/roadeye-api-hq/build/libs/app.jar
        run: |
          echo "${{ env.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem ${{ env.JAR_PATH }} ${{ env.USERNAME }}@${{ env.HOST }}:~/app/roadeye/api-hq/.deploy/next.jar
          ssh -i private_key.pem ${{ env.USERNAME }}@${{ env.HOST }} "~/app/roadeye/api-hq/deploy.sh"
          rm private_key.pem
